### ISSUE TITLE
Push Notifications - Yun

### ISSUE THREAD

**Issue by jeffreyjackson** [ParsePlatform/parse-embedded-sdks#26]
The sample project works great, and I'm able to execute "Test".  This push is received and it looks like everything is working just fine.  However, when I go to send my own push notification from the web panel it says I don't have any registered devices... what gives?

**Comment by jeffreyjackson** [comment]
Actually - do I need to setup a certificate?

**Comment by ronaldyang** [comment]
@jeffreyjackson  This is probably due to the Parse app finds there is no device(Android/iOS) for push, although you actually have a device(embedded) registered.  There are two work arounds here:
1.  run following command in your terminal
curl -X POST \
 -H "X-Parse-Application-Id:  YOUR_APP_ID" \
 -H "X-Parse-Client-Key: YOUR_CLIENT_KEY" \
 -H "Content-Type: application/json" \
 -d '{
 "where": {"deviceType": "embedded"
 },
 "data": {
 "alert": "blink"
 }
 }' \
 https://api.parse.com/1/push

2. Manually create an  installation object with "deviceType" as "android" or "ios".

**Comment by embeddedgeeks** [comment]
This does not work ! please fix this issue the embedded parse sdk is worthless withou push notifications!!

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by stanleyw** [comment]
Same issue as #46
